- name: crete Jenkins Jobs
  hosts: localhost
  roles:
     - jenkins

#  vars:
#     folders:
#        - { folder_name: "CI-Pipelines" }
#        - { folder_name: "Infra-Jobs" }
#        - { folder_name: "Deployment-Jobs" }

  vars:
     folders:
        - { folder_name: "CI-Pipelines" }
        - { folder_name: "Deployment jobs" }
