- name: copy config file - {{ item.folder_name }}
  ansible.builtin.template:
     src: folder.xml
     dest: /tmp/folder.xml

- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
     config: "{{ lookup('file', '/tmp/folder.xml') }}"
     name: {{ item.folder_name }}
     password: admin123
     url: http://localhost:8080
     user: admin